Removed the reductant Column names in Snapshot Bronze
databrickslabs/overwatch pull request #1193
Opened 2024-04-30 20:28 UTC by souravbaner-da

Handle Reductant Column Names from cluster_snapshot_bronze

2024-05-01 18:00 UTC, gueniai requested changes

2024-05-01 18:00 UTC, gueniai commented on src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala
> +          var finalDF = outputDF.withColumn("default_tags", SchemaTools.structToMap(outputDF, "default_tags"))
This can go back to a val now

2024-05-01 18:00 UTC, gueniai commented on src/main/scala/com/databricks/labs/overwatch/pipeline/TransformFunctions.scala
> +  def standardizeFieldInStruct(df: DataFrame, structColName: String, oldFieldName: String, newFieldName: String): DataFrame = {
this is no longer used

2024-05-01 18:03 UTC, souravbaner-da commented on src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala
> +          var finalDF = outputDF.withColumn("default_tags", SchemaTools.structToMap(outputDF, "default_tags"))
Done

2024-05-01 18:03 UTC, souravbaner-da commented on src/main/scala/com/databricks/labs/overwatch/pipeline/TransformFunctions.scala
> +  def standardizeFieldInStruct(df: DataFrame, structColName: String, oldFieldName: String, newFieldName: String): DataFrame = {
Done

2024-05-03 12:27 UTC, gueniai approved these changes

2024-05-03 12:27 UTC, merged