docs for warehouse cost
databrickslabs/overwatch pull request #1286
Opened 2024-09-23 17:03 UTC by aman-db

closes #1261

2024-09-23 21:14 UTC, neilbest-db requested changes
Please see comments on respective files.

2024-09-24 06:15 UTC, aman-db commented on docs-compose/overwatch_docs/content/DataEngineer/Definitions/_index.md
>  * [warehouse](#warehouse)
done

2024-09-24 06:15 UTC, aman-db commented on docs-compose/overwatch_docs/content/DataEngineer/Definitions/_index.md
> +#### warehouseDbuDetails
done

2024-09-24 06:15 UTC, aman-db commented on docs-compose/overwatch_docs/content/DataEngineer/Definitions/_index.md
> +#### WarehouseStateFact
done

2024-09-24 06:16 UTC, aman-db commented on docs-compose/overwatch_docs/static/images/_index/Overwatch_Gold_0.8.2.0.png
let me know if it needs to be removed we need to make changes in the lucid chart

2024-09-24 06:16 UTC, aman-db commented on docs/images/_index/Overwatch_Gold_0.8.2.0.png
no , we need to make changes in the lucid chart , export it as a image and use here

2024-09-24 15:22 UTC, neilbest-db approved these changes

2024-09-24 19:07 UTC, merged