OV-382-INITIALIZE-CLASS-TEST-CASES
databrickslabs/overwatch pull request #407
Opened 2022-05-24 11:41 UTC by saswatdb

closes #382

2022-06-09 21:38 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Initializer.scala
> +        val createConsumerDBSTMT = if (!config.isLocalTesting) {
can we not set the location as a relative path in the config for local testing and not need a different logic branch for this?

2022-06-09 21:38 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Initializer.scala
> +        val createConsumerDBSTMT = if (!config.isLocalTesting) {
can we not set the location as a relative path in the config for local testing and not need a different logic branch for this?

2022-06-09 21:38 UTC, GeekSheikh commented on src/test/scala/com/databricks/labs/overwatch/pipeline/InitializeTest.scala
> +  }
I think we should add a positive test case as well. i.e. where orgID has ilb in it

2022-06-09 21:38 UTC, GeekSheikh commented on src/test/scala/com/databricks/labs/overwatch/pipeline/InitializeTest.scala
> +  }
I think we should add a positive test case as well. i.e. where orgID has ilb in it

2022-06-09 21:38 UTC, GeekSheikh commented on src/test/scala/com/databricks/labs/overwatch/pipeline/InitializeTest.scala
> +      val databases = spark.sql("show databases").select("namespace").map(f => f.getString(0)).collect()
what is this `select("namespace")`? It doesn't work on Databricks, not sure what you're getting here. I think `show databases` returns a column named `databaseName`

2022-06-09 21:38 UTC, GeekSheikh commented on src/test/scala/com/databricks/labs/overwatch/pipeline/InitializeTest.scala
> +      val databases = spark.sql("show databases").select("namespace").map(f => f.getString(0)).collect()
what is this `select("namespace")`? It doesn't work on Databricks, not sure what you're getting here. I think `show databases` returns a column named `databaseName`

2022-06-09 21:38 UTC, GeekSheikh commented on src/test/scala/com/databricks/labs/overwatch/pipeline/InitializeTest.scala
> +  describe("Tests for validateAndRegisterArgs function") {
Some additional tests are needed.

- test for missing parameters
- test for duplicate parameters
- test for non-escaped json
- test for malformed json

2022-06-09 21:38 UTC, GeekSheikh commented on src/test/scala/com/databricks/labs/overwatch/pipeline/InitializeTest.scala
> +    it("dataTargetIsValid function should throw exception when the current db is not created from overwatch") {
more tests:

- use initializeDatabase to create a database that is owned by overwatch and validate that it works as expected.
- additional tests around initDatabase and validate DataTarget for schema tests
- I don't see any tests for the metadata checks
- what if consumerDB is left blank in config -- does it work as expected (i.e. etl and consumer dbs are the same)?

I think there are likely more scenarios than this even...I want to make sure and have good coverage on `initDatabase` and `validateDataTarget`. Please feel free to ask some questions but I think if you review the code a little deeper you can find quite a few more cases.

2022-06-09 21:38 UTC, GeekSheikh commented on src/test/scala/com/databricks/labs/overwatch/pipeline/InitializeTest.scala
> +    it("validateScope function should check if sparkEvents, clusterEvents, and jobs scopes require clusters scope") {
We need a lot more test cases here:

- I think I see 3 dependency chains here -- we should test them all independently 
- There's at least 1 more where all scopes are valid (positive test case)
- We need case sensitivity tests
- Seq[String] should maintain order, can we validate that? Are there any order dependencies that could break the logic chain?

2022-06-29 18:14 UTC, GeekSheikh reviewed
Thank you for the updates. The PR is looking good but now 4 tests are failing, can you fix these up?

```
- validateAuditLogConfigs function validate audit log format in the config  *** FAILED ***
[info]   Expected exception com.databricks.labs.overwatch.utils.BadConfigException to be thrown, but java.lang.NullPointerException was thrown (InitializeTest.scala:159)
[info] Tests for validateAndRegisterArgs function
[info] - validateAndRegisterArgs function should validate and register variables on the conf *** FAILED ***
[info]   java.lang.NullPointerException:
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.lang.reflect.Method.invoke(Method.java:498)
[info]   at com.databricks.dbutils_v1.DBUtilsHolder$$anon$1.invoke(DBUtilsHolder.scala:17)
[info]   at com.sun.proxy.$Proxy18.secrets(Unknown Source)
[info]   at com.databricks.labs.overwatch.pipeline.Initializer.com$databricks$labs$overwatch$pipeline$Initializer$$validateAndRegisterArgs(Initializer.scala:313)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   ...
[info] - validateAndRegisterArgs function should fail when a parameter is missing *** FAILED ***
```

2022-06-29 18:14 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Initializer.scala
> +    if (!disableValidations && !config.isLocalTesting) { // temp working dir is not necessary for disabled validations as pipelines cannot be
ah gotcha. I'm interested to know if we can get rid of these local testing checks eventually but for now this is good. Thank you.

2022-06-30 07:08 UTC, saswatdb commented
> 

All 22 test cases getting passed for me, have we set these environment variables : 
OVERWATCH=LOCAL;OVERWATCH_ENV=demo;OVERWATCH_TOKEN=dapi6b1226434461814e7bh43

2022-08-11 16:10 UTC, GeekSheikh requested changes
@saswatdb There are 4 tests failing wrt to Initializer tests -- could you please fix these

2022-08-25 12:21 UTC, souravbaner-da commented
Hi @GeekSheikh it seems all the test cases are running successfully after providing the env variables as below:
```
OVERWATCH_ENV=demo;
OVERWATCH_TOKEN=dapi6b1226434461814effff;
OVERWATCH=LOCAL
```

Do we have to provide the same during our deployment also as in Local all are working fine.

2022-08-25 12:22 UTC, souravbaner-da commented
Attached is the screenshot for the same

![image](https://user-images.githubusercontent.com/109206082/186663132-813f8908-0be9-442b-af55-8f5f856629aa.png)

2022-08-26 12:57 UTC, GeekSheikh commented
Reminder - Add docs to tests folder README.md

Add details to building.md
Add reference and build summary with links in /readme.md

2022-09-08 16:30 UTC, GeekSheikh approved these changes
I would like to review a few of these ignored tests again later and see if we can't make them work outside of full pipeline but looks good approving.

2022-09-08 16:33 UTC, merged