Refractor Initializer
databrickslabs/overwatch pull request #683
Opened 2023-01-09 16:14 UTC by souravbaner-da

Refractor Initializer

2023-01-09 21:17 UTC, GeekSheikh requested changes
cursory analysis looks good. Please re-submit for review after @sriram251-code review is complete and requested PR Proof notebooks are completed and vetted.

2023-01-09 21:17 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Initializer.scala
> +    }
let's remove this reference as isLocalTesting is deprecated. Let's just continue to use the `getOrgId` function as we are below.

2023-01-11 07:34 UTC, souravbaner-da commented
Close #677

2023-02-17 08:42 UTC, souravbaner-da commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Initializer.scala
> +    config.setInputConfig(rawParams)
@sriram251-code Done

2023-02-17 08:45 UTC, souravbaner-da commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Initializer.scala
> -
@sriram251-code  this has been moved to InitializerFunctions.scala

2023-02-17 08:53 UTC, souravbaner-da commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Initializer.scala
> +    val validatedTempWorkingDir = Init.validateTempWorkingDir(rawTempWorkingDir)
@sriram251-code Done. Changed to prepTempWorkingDir

2023-02-17 09:06 UTC, souravbaner-da commented on src/main/scala/com/databricks/labs/overwatch/pipeline/InitializerFunctions.scala
> +      if (tokenSecret.nonEmpty && !disableValidations && !config.isLocalTesting) {
@sriram251-code  Done

2023-02-17 09:07 UTC, souravbaner-da commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Initializer.scala
>      if (dbutils.notebook.getContext.tags("orgId") == "0") {
Already done in another issue https://github.com/databrickslabs/overwatch/issues/115

2023-02-17 09:07 UTC, souravbaner-da commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Initializer.scala
> +    print("tags are ", dbutils.notebook.getContext.tags)
@sriram251-code  done

2023-02-17 09:07 UTC, souravbaner-da commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Initializer.scala
>      config.setMaxDays(rawParams.maxDaysToLoad)
Could you please let me know the logic if maxDaysToLoad would be 0 or negative number?

2023-02-17 09:14 UTC, souravbaner-da commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Initializer.scala
>      config.setMaxDays(rawParams.maxDaysToLoad)
As per discussion done the changes

2023-02-28 13:56 UTC, sriram251-code approved these changes

2023-02-28 20:17 UTC, GeekSheikh approved these changes

2023-02-28 20:24 UTC, merged