enabled remote getWorkspaceByDatabase
databrickslabs/overwatch pull request #754
Opened 2023-02-16 15:44 UTC by GeekSheikh

closes #750

2023-02-17 14:04 UTC, sriram251-code requested changes

2023-02-17 14:04 UTC, sriram251-code commented on src/main/scala/com/databricks/labs/overwatch/utils/Tools.scala
> +                              successfullOnly: Boolean = true,
successfullOnly what is the use of this field???

2023-02-20 05:11 UTC, brij-raghuwanshi-db requested changes
How or where are we getting the apiURL for remote workspaces?

2023-02-20 06:17 UTC, sriram251-code approved these changes

2023-02-20 14:18 UTC, GeekSheikh commented
> How or where are we getting the apiURL for remote workspaces?

@brij-raghuwanshi-db here the user must look up the orgid and apiURL from their config to instantiate the remote workspace.

2023-02-20 14:20 UTC, brij-raghuwanshi-db approved these changes
Looks good.

2023-02-20 14:24 UTC, merged