622 verbose audit logging
databrickslabs/overwatch pull request #801
Opened 2023-03-06 13:24 UTC by souravbaner-da

Add Verbose Audit Log

2023-03-15 18:17 UTC, GeekSheikh requested changes
ultimately this needs to either be a materialized target with appropriate incremental loads OR it needs to be a view -- we can't just throw a function at the end to build stuff. This won't be maintainable and doesn't fit in with the rest of the pipeline.

2023-03-15 18:17 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala
> +      notebookCodeAndMetaDF.write.format("delta").mode("overwrite").save(s"${config.etlDataPathPrefix}/verbose_audit_log")
If you're going to materialize this -- you need to create a target and do incrementals -- doing a full compute and overwrite each time will crush perf in most customers. If you don't want / need to materialize this data you can just create a view.

2023-03-15 18:17 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala
> +    publishVerbose()
There's no try/catch here at all -- so if something were to fail in this function it would break the pipeline.

2023-03-15 18:17 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala
> +      & (spark.catalog.tableExists("overwatch_dev_5481.notebook"))) {
you have direct references to database name here.

2023-04-10 20:30 UTC, GeekSheikh requested changes

2023-04-10 20:30 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala
> +      val ColNames = Array(
any metric field name like execution_time should have UOM (unit of Measure) in this case it is _s

executionTime --> execution_time_S
execution_estimated_cost --> estimated_dbu_cost

2023-04-10 20:30 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala
> +      notebookCodeAndMetaDF.write.format("delta").mode("overwrite").save(s"${config.etlDataPathPrefix}/verbose_audit_log")
See my earlier comment -- please follow the pipeline pattern

2023-04-10 20:30 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala
> +      spark.sql(s"create or replace view ${config.consumerDatabaseName}.verbose_audit_log as select * from delta.`${config.etlDataPathPrefix}/verbose_audit_log`")
you need to follow the pipeline pattern here too -- you're missing partition filter push down by doing it this way -- something that is natively handled for you if you just add this to the standard view publication pattern.

2023-04-10 20:30 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala
> +    verboseAudit()
This should not be here -- when you follow the pattern this logic will become part of refreshViews. 

Just add case to the very end and make a complex case statement
case audit + notebooks + clusterEvents --> publish this view

...
case audit & notebooks & clusterEvents => {GoldTargets.viewTarget.publish(...)}

The above is obviously pseudocode -- you may have to do a logical operator func and use if for this case

2023-04-10 20:30 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala
> +          GoldTargets.clusterStateFactTarget
this must be incremental DFs

CLSF should have lag of 30d to ensure long-running states are within scope but not forever history

2023-04-10 20:30 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala
> +  protected def buildVerboseAudit(
This looks a lot better than all of the logic being in gold -- not sure why the logic is all duplicated -- Please take the requested changes from Gold.scala and implement there here

2023-04-10 20:30 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala
> +        .withColumn("totalCostPMS", col("uptime_in_state_H") / col("total_cost") / lit(60) / lit(60) / lit(1000))
I believe this logic is off as the final cost metric is showing very silly numbers.

2023-04-10 20:30 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala
> +      val ColNames = Array(
don't start a variable with a capital letter

2023-04-10 20:30 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala
> +      val ColNames = Array(
what is shardName and why is it here? It seems to always be null and shouldn't it basically be the same thing as workspace_name (semantically)? Suggest remove this field and only use workspace_name

2023-04-10 20:30 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineTargets.scala
> +    lazy private[overwatch] val verboseAuditTarget: PipelineTable = PipelineTable(
if you continue to use MERGE -- _permitDuplicateKeys should be false unless I'm missing something

2023-04-10 20:30 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineTargets.scala
> +      zOrderBy = Array("notebookId", "unixTimeMS")
zorders are expensive and I don't really see many people (or downstream ETLs) referencing notebookId or unixTimeMS heavily, do you? Zorders are meant to speed up ETL and/or end-user queries -- I foresee people filtering on notebookPath and using wildcards and/or the actual timestamp column much more than unixTimeMS. 

If you agree -- I suggest removing these orders -- if you disagree, please make your case and we can review.

2023-04-10 20:30 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineTargets.scala
> +      _keys = Array("organization_id", "timestamp", "unixTimeMS"),
why are timestamp AND unixTimeMS BOTH keys? unixTimeMS is the same as timestamp but with slightly higher resolution -- as such remove timestamp from keys.

2023-04-10 20:30 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineTargets.scala
> +      _mode = WriteMode.merge,
Why MERGE? Merge is very expensive and the actions are immutable right? By removing dbsql -- you can get rid of potentially getting a start in overwatch run 1 and a finish in run 2 and greatly simplify this. All of the DBSQL query information is captured in SQL_query_history table (and more); thus it doesn't need to be captured here.

2023-04-10 20:30 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineTargets.scala
> +      name = "verboseAuditTarget_gold",
change this name to something friendlier...perhaps notebookCommands_gold (feel free to find something better)

certainly we don't want to put the word "audit" in a gold table -- customers may have misplaced expectations

2023-04-10 20:30 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/PipelineTargets.scala
> +      name = "verboseAuditTarget",
change name to be appropriate for whatever you wind up naming the gold table, just remove _gold

2023-04-27 05:02 UTC, souravbaner-da commented on src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala
> +      val notebookCodeAndMetaDF = spark.sql(s"SELECT * FROM delta.`${config.etlDataPathPrefix}/audit_log_bronze`")
Do we need to expose custom_tags here in this table

2023-05-16 06:34 UTC, souravbaner-da commented
Duplicate PR already there #917

2023-05-16 06:34 UTC, closed without merging