Null spark executor issue resolved
databrickslabs/overwatch pull request #935
Opened 2023-05-16 09:10 UTC by sriram251-code

closes #903

2023-05-16 09:32 UTC, souravbaner-da requested changes
@Sriram-databricks    Please remove unnecessary debug print statement

2023-05-16 09:41 UTC, souravbaner-da approved these changes

2023-05-18 13:59 UTC, GeekSheikh requested changes

2023-05-18 13:59 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala
> +         logger.log(Level.INFO, s"SPARK CASE SENSITIVITY - POS1: THREAD: ${Thread.currentThread()} --> ${sparkCaseSensitiveValueDebug()}")
these 4 POS logs were just for debugging, let's remove these.

2023-05-18 13:59 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala
> +            .withColumn("DerivedTimestamp", fixDupTimestamps)
This is a great idea. I'm thinking we might should do something similar for all the complex field derivations. The stageId derivation could be getting null for a similar reason.

What I mean by something similar is give them a temporary column name and then rename them, drop the originals and rename it back to the target name.

* executorIdOverride
* progressCol
* stageIDColumnOverride
* stageAttemptIDColumnOverride

2023-05-30 13:29 UTC, sriram251-code commented
duplicate of https://github.com/databrickslabs/overwatch/pull/940.
I have moved the review comments to 940 PR.

Closing it.

2023-05-30 13:29 UTC, closed without merging