Added filter for response Code 200
databrickslabs/overwatch pull request #955
Opened 2023-06-08 08:49 UTC by souravbaner-da

Added Condition for 200 Status code in SilverTransform.Scala.

Close #901

2023-06-08 19:28 UTC, GeekSheikh requested changes
super minor changes -- philosophically I think we want to keep the unsuccessful account login and account mod attempts in gold. Failed account mods and logins are very important within the context of these tables. I don't want customers to have to go back to bronze to find these.

2023-06-08 19:28 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/SilverTransforms.scala
> +      .filter(responseSuccessFilter)
remove this

2023-06-08 19:28 UTC, GeekSheikh commented on src/main/scala/com/databricks/labs/overwatch/pipeline/SilverTransforms.scala
> +      .filter(responseSuccessFilter)
remove this

2023-06-09 06:44 UTC, souravbaner-da commented on src/main/scala/com/databricks/labs/overwatch/pipeline/SilverTransforms.scala
> +      .filter(responseSuccessFilter)
Done

2023-06-09 06:45 UTC, souravbaner-da commented on src/main/scala/com/databricks/labs/overwatch/pipeline/SilverTransforms.scala
> +      .filter(responseSuccessFilter)
Done

2023-06-14 14:15 UTC, GeekSheikh approved these changes

2023-06-14 14:15 UTC, merged